---
title: "An Interactive Tool for Understanding Machine Learning Results for Imbalanced Data"
output: 
  flexdashboard::flex_dashboard:
    theme: 
      version: 4
      bootswatch: simplex
    includes: 
      after_body: "busy.html"
runtime: shiny
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(caret)
library(plotly)
library(shiny)
library(flexdashboard)
library(DT)
library(fontawesome)

source('custom_functions_app.R')

```


## Sidebar {.sidebar}

**Required Inputs:**


```{r shiny_inputs}
numericInput(
  'sim_num',
  label = 'Simulation Replications:',
  value = 10^3,
  min = 10^3,
  max = 10^5,
  step = 1000,
  width = NULL
)

numericInput(
  'num_classes',
  label = 'Number of Classes:',
  value = 2,
  min = 2,
  max = 20,
  step = 1,
  width = NULL
)


numericInput(
  'num_observations',
  label = 'Number of Observations:',
  value = 100,
  min = 100,
  max = 10^5,
  step = 1,
  width = NULL
)


numericInput(
  'first_class_perc',
  label = 'Proportion of Reference Class:',
  value = 0.2,
  min = 0.001,
  max = 0.5,
  step = NA,
  width = NULL
)


selectInput(inputId = 'pred_approach', 
            label = 'Prediction Approach',
            choices = c('uniform', 'proportional'),
            selected = 'proportional')


numericInput(
  'histogram_percentile',
  label = 'Percentile on Histograms:',
  value = 0.95,
  min = 0,
  max = 1,
  step = NA,
  width = NULL
)
```


---

<br>

**Created by:**   
[Fadel M. Megahed](https://miamioh.edu/fsb/directory/?up=/directory/megahefm)  
[Ying-Ju (Tessa) Chen](https://udayton.edu/directory/artssciences/mathematics/chen-ying-ju.php)  
[Allison Jones-Farmer](https://miamioh.edu/fsb/directory/?up=/directory/farmerl2)     
[Steven E. Rigdon](https://www.slu.edu/public-health-social-justice/faculty/rigdon-steven.php)

**Version:** 0.1.0

**Last Updated:** `r format(Sys.Date(), format = "%b %d, %Y")`


---

<br>

**Correspondence:**

`r fa("inbox", fill = "steelblue")` $~$ [fmegahed\@miamioh.edu](mailto:fmegahed@miamioh.edu)

`r fa("twitter", fill = "steelblue")` $~$ [\@FadelMegahed](https://twitter.com/fadelmegahed)

`r fa("github", fill = "steelblue")` $~$ [\@fmegahed](https://github.com/fmegahed)


## Column
  
### Summary of Simulation Results
  
```{r simulation}

# The five experimental conditions:
# _________________________________

input_sim_num = reactive( x = 1:as.numeric(input$sim_num) )
input_num_classes = reactive( x = as.numeric(input$num_classes) )
input_num_observations = reactive( x = as.numeric(input$num_observations) )
input_first_class_perc = reactive( x = as.numeric(input$first_class_perc) )
input_pred_approach = reactive(x = as.character(input$pred_approach))
input_histogram_percentile = reactive(x = as.numeric(input$histogram_percentile))


sim_setup = reactive({
  sim_grid = expand_grid(
    input_sim_num(), 
    input_num_classes(), 
    input_num_observations(), 
    input_first_class_perc(),
    input_pred_approach()
  ) 
  
  colnames(sim_grid) = c('sim_num', 'num_classes', 'num_observations',
                         'first_class_perc', 'pred_approach')
  
  sim_grid %>%
    group_by_at( vars(-sim_num ) ) %>% 
    # using the dplyr::cur_group_id() to create the IDs
    mutate( exp_num = cur_group_id() ) %>% 
    # ungrouping since it was only performed to create unique ids
    ungroup() %>% 
    # moving the exp_num to the beginning
    relocate( exp_num )  %>% 
    # creating list columns for all the columns with except of ID-type columns
    nest(data = any_of( c('num_classes', 'num_observations',
                         'first_class_perc', 'pred_approach') ) ) %>% 
    arrange( exp_num ) -> sim_setup
  
  return(sim_setup)
})

# reactive(write_rds( sim_setup(), 'sim_setup.rds'  ))


experimental_results = reactive({
  results = sim_setup() %>% 
  mutate(
    acc_metrics = map(.x = data, .f = sim_function, base_class_name = 'class_')
  )
  
  return(results)
})

# reactive(write_rds( experimental_results(), 'experimental_results.rds'  ))


summary_results = reactive({
   experimental_results() %>% 
  # unnesting the acc_metrics (i.e., generating columns for each of the metrics)
  unnest( acc_metrics ) %>% 
  # grouping by exp_num 
  # (and data which is redundant but to keep it in the summary table)
  group_by(exp_num, data) %>% 
  # creating summaries of means and sds for each of the metrics by exp_num
  summarise(
    across(accuracy:f_measure,  
           list(mean = ~ mean(.x, na.rm = TRUE),
                sd = ~ sd(.x, na.rm = TRUE)), .names = "{.fn}_{.col}" )
  ) %>% 
  # expanding the data into the different experimental conditions for interpretation
  unnest(data)
})

# reactive(write_rds( summary_results(), 'summary_results.rds'  ))
 


renderUI({
  
  results = summary_results()
  
  line1 = '<font size="5"><b>Your selected inputs:</b></font>'
  line2 = paste0('<b>Number of simulations:</b>  ', scales::comma( max( input_sim_num() ) ) )
  line3 = paste0('<b>Number of classes:</b>  ', input_num_classes())
  line4 = paste0('<b>Number of observations:</b>  ', scales::comma(input_num_observations()) )
  line5 = paste0('<b>Reference class proportion:</b>  ', input_first_class_perc())
  line6 = paste0('<b>Prediction approach:</b>  ', input_pred_approach())
  line7 = paste0('<b>Percentile on histograms:</b>  ',
                 input_histogram_percentile())
  line8 = ' '
  line9 = '<font size = "5"><b>A summary of the simulation results:</b></font>'
  line10 = paste0('<b>Accuracy:</b>  ', round(results$mean_accuracy, 3), ' +/- ',
                 round(results$sd_accuracy, 3))
  line11 = paste0('<b>Sensitivity:</b>  ', round(results$mean_sensitivity, 3), ' +/- ',
                 round(results$sd_sensitivity, 3))
  line12 = paste0('<b>Specificity:</b>  ', round(results$mean_specificity, 3), ' +/- ',
                 round(results$sd_specificity, 3))
  line13 = paste0('<b>Geometric mean:</b>  ', round(results$mean_g_mean, 3), ' +/- ',
                 round(results$sd_g_mean, 3))
  line14 = paste0('<b>Precision:</b>  ', round(results$mean_precision, 3), ' +/- ',
                 round(results$sd_precision, 3))
  line15 = paste0('<b>Recall:</b>  ', round(results$mean_recall, 3), ' +/- ',
                 round(results$sd_recall, 3)) 
  line16 = paste0('<b>F1 score:</b>  ', round(results$mean_f_measure, 3), ' +/- ',
                 round(results$sd_f_measure, 3))
  
  HTML(paste(line1, line2, line3, line4, line5, line6, line7,
             line8, line9, line10, line11, line12, line13, 
             line14, line15, line16,
             sep = '<br/>'))
}
)



```

### Histogram of the Results

```{r histogram_plot}
df_mean = reactive({
  experimental_results() %>% 
    # unnesting the acc_metrics (i.e., generating columns for each of the metrics)
  unnest( acc_metrics ) %>% 
    select(-data) %>% 
    pivot_longer(cols = accuracy:g_mean, names_to = 'metric') %>% 
    ungroup() %>% 
    group_by(metric) %>% 
    summarise(
      mean = mean(value, na.rm = T) %>% round(digits = 3), 
      percentile = quantile(value, input_histogram_percentile(), na.rm=T) %>% round(digits =3)) %>% 
    filter(metric != 'f_measure')
})

plot_data = reactive({
  experimental_results() %>% 
    # unnesting the acc_metrics (i.e., generating columns for each of the metrics)
  unnest( acc_metrics ) %>% 
    select(-data) %>% 
    pivot_longer(cols = accuracy:g_mean, names_to = 'metric')
})


renderPlotly({
  plot_data() %>% 
    filter(metric != 'f_measure') %>% 
    ggplot(aes(x = value, group = metric)) +
    facet_wrap(~ metric, scales = 'fixed') +
  geom_histogram(aes(fill = as.factor(metric)), binwidth = 0.01, color = 'black') +
  geom_vline(data = df_mean(), 
             aes(xintercept = mean), col='black', size = 1.75, linetype = 'dotdash') + 
  geom_vline(data = df_mean(),
             aes(xintercept = percentile), col="#E7298A", size=1.75, linetype = 'dotted') + 
  scale_x_continuous(breaks = scales::pretty_breaks(10), limits = c(0,1)) +
  scale_y_continuous(breaks = scales::pretty_breaks(5), labels = scales::comma) +
  scale_fill_brewer(palette = "Paired") +
  scale_color_brewer(palette = "Paired") +
  theme_bw() +
  theme(legend.position = 'none') + 
  labs(x = 'Metric Values', y = 'Count', 
       title = paste('A histogram of the predictive metric values based on',
                     scales::comma(input_sim_num() %>% max()), 'simulation runs',
                     'with proportion of reference class of', 
                     input_first_class_perc(), 'and the',
                     paste0('"', input_pred_approach(), '"'), 'predictive strategy')) -> p
  
  plotly::ggplotly()
})
```
